Makefile.am, doc/zmq_getsockopt.txt, include/zmq.h, src/i_engine.hpp, src/pipe.cpp, src/pipe.hpp, src/router.cpp, src/router.hpp, src/session_base.cpp, src/socket_base.cpp, src/socket_base.hpp, src/stream_engine.hpp
Revert "linking fd to pipe identity via socket option"
This reverts commit fe3e8c5c70dc3fbcb0244c5f4c52dcd71b80f858.
Conflicts:
include/zmq.h
src/pipe.hpp
src/session_base.cpp
=> resolve #1296 Remove of ZMQ_IDENTITY_FD socket option

include/zmq.h
Solution: backport the latest STDINT definitions from libzmq.
Fixes #34
=> Problem: event interface isn't compatible with CZMQ 3.0

configure.ac
Solution: bump to ABI version 5
=> Problem: 4.1 broke the ABI yet did not bump ABI number

builds/redhat/zeromq.spec.in
Fixes a packaging error when building the RPM:
```
$ rpmbuild -tb --with libsodium zeromq-4.1.2.tar.gz
[…]
RPM build errors:
File not found: …/zeromq-4.1.2-1.el6.x86_64/usr/lib64/libzmq.so.4
File not found: …/zeromq-4.1.2-1.el6.x86_64/usr/lib64/libzmq.so.4.0.0
$ ls …/zeromq-4.1.2-1.el6.x86_64/usr/lib64/libzmq*
libzmq.a  libzmq.la  libzmq.so  libzmq.so.5  libzmq.so.5.0.0
```
=> Fix path to libzmq .so files in RPM spec file

doc/zmq_ctx_set.txt
Documentation of ZMQ_THREAD_SCHED_POLICY and ZMQ_THREAD_PRIORITY context's option.
I use both these options on linux kernel preempt_rt with SCHED_FIFO value and it works as I described it.
=> THREAD_SCHED_POLICY & THREAD_PRIORITY documentation

autogen.sh
Autogen.sh looks for the libtool command as a mean to check if
libtool is available. But distributions like Debian and Ubuntu have
split the libtool package, and the libtool script is now in a
separate package. The solution is to look for the libtoolize command
too before failing, which is what the Autotools chain actually needs
on Linux. Keep checking for libtool to be compatible with OSX, where
the opposite is true.
=> Solution: check for libtoolize in autogen. Fixes #54

.travis.yml
This PR makes the CI build scripts compatible with OSX on Travis. Fixes #56. Note that until OSX build is enabled on a project by emailing support@travis-ci.com, the option in travis.yml will have no effect.
=> Travis ci osx

tests/test_connect_delay_tipc.cpp, tests/test_filter_ipc.cpp, tests/test_immediate.cpp, tests/test_req_relaxed.cpp, tests/test_security_curve.cpp, tests/test_security_null.cpp, tests/test_security_plain.cpp, tests/test_spec_dealer.cpp, tests/test_spec_pushpull.cpp, tests/test_spec_rep.cpp, tests/test_spec_req.cpp, tests/test_spec_router.cpp, tests/testutil.hpp
Solution: cherry-pick Pieter Hintjens commit a7a512ab from libzmq
repository to increase test timeouts to 250 msec.
Cherry-picked from: https://github.com/zeromq/libzmq/commit/a7a512ab
=> Problem: CI may fail due to timeout. Fixes #58

doc/zmq_setsockopt.txt
Full message is actually (request id, identity, 0,
user frames...).
=> Fix documentation of the ZMQ_REQ_CORRELATE option.

.travis.yml
Hello,
As discussed in https://github.com/zeromq/libzmq/pull/1529 here's a PR to switch from VM to container based Travis CI builds. Needed changes were removing "sudo" and installing in local directory rather than in the default /usr/local.
=> Enable container-based build

CMakeLists.txt
Check for actual functions in ws2_32, ws2, rpcrt4, iphlpapi instead of printf.
MSVC 2015 has C runtime globally refactored. Looks like these libraries don't explicitly require msvcrt anymore, which contained printf.
=> Fix CMake configuration issue with MSVC 2015.

builds/cmake/Modules/FindAsciiDoc.cmake
Fixed '(' and ')' braces usage volation according to CMake policy CMP0053 in FindAsciiDoc module.
```
CMake Warning (dev) at builds/cmake/Modules/FindAsciiDoc.cmake:9 (find_program):
Policy CMP0053 is not set: Simplify variable reference and escape sequence
evaluation.  Run "cmake --help-policy CMP0053" for policy details.  Use the
cmake_policy command to set the policy and suppress this warning.
For input:
'$ENV{PROGRAMFILES(X86)}/asciidoc'
the old evaluation rules produce:
'C:\Program Files (x86)/asciidoc'
but the new evaluation rules produce an error:
Syntax error in cmake code at
C:/Projects/forks/zeromq4-1/builds/cmake/Modules/FindAsciiDoc.cmake:13
when parsing string
$ENV{PROGRAMFILES(X86)}/asciidoc
Invalid character ('(') in a variable name: 'PROGRAMFILES'
Using the old result for …
```
=> Fix FindAsciiDoc module for CMake 3

src/stdint.hpp
VS2008 doesn't have a proper stdint.h
Reverts #42 
closes zeromq/libzmq#1630
=> Revert "stdint.h is available in VS2008 (1500)"

src/curve_client.cpp, src/curve_server.cpp
There are two todo comments in curve_client.cpp and curve_server.cpp that suggest
checking the return code of sodium_init() call. sodium_init() returns -1 on error,
0 on success and 1 if it has been called before and is already initalized:
https://github.com/jedisct1/libsodium/blob/master/src/libsodium/sodium/core.c
=> Problem: return code of sodium_init() is not checked.

include/zmq.h
where stdint.h is unavailable
(see stdint.hpp for the same check)
fixes regression in #35
=> don't include stdint.h on msc < 1600

src/socket_base.cpp, src/tcp_address.cpp, src/windows.hpp
This broke compatibility with Windows XP and went against our "only bug fixes" policy for stable releases.
=> Reverted patch for IPv6 support

tweetnacl/contrib/randombytes/winrandom.c
failure check for returncode was inverted, causing an infinite loop.
backport of patch in zeromq/libzmq#1621
=> backport winrandom fix

src/windows.hpp
if_nametoindex requires minimum windows version vista, which is 0x0600.
additionally, mingw defines _WIN32_WINNT as 0x0501, and the preprocessor will decide that 0x0501 is acceptable per the code, but will fail compilation.
unless there is a way to disable the newer client-server model (i believe this is what uses if_nametoindex) then the minimum version for 4.1.4 and onwards needs to be bumped to _WIN32_WINNT >= 0x0600
=> update minimum _WIN32_WINNT version to 0x0600 for 4.1.4 onwards

src/windows.hpp
Reverts zeromq/zeromq4-1#95
That PR was meant to fix the use of `if_nametoindex`, which has been removed specifically so this change would not be necessary.
=> Revert "update minimum _WIN32_WINNT version to 0x0600 for 4.1.4 onwards"

src/zmq.cpp
Solution: backport https://github.com/zeromq/libzmq/commit/992ac3baa86cb03b4284c35b5a72154e9303f08f merged via https://github.com/zeromq/libzmq/pull/1593
=> Problem: build broken with gcc 6

.travis.yml, src/options.cpp
Solution: backport from https://github.com/zeromq/libzmq/pull/1805 together with a small fix for Travis CI.
=> Problem: curve keys getsockopt uninitialised read

src/curve_client.cpp, src/curve_server.cpp, tests/test_security_curve.cpp
Libsodium has started returning -1 in some cases.
Solution: allow and handle error returns from these calls.
Fixes #1831
=> Problem: can't be sure crypto_box always returns 0

CMakeLists.txt, Makefile.am, NEWS, configure.ac, src/ctx.cpp, src/curve_client.cpp, src/curve_client.hpp, src/curve_server.cpp, src/curve_server.hpp, src/options.cpp, src/stream_engine.cpp, src/zmq.cpp, src/zmq_utils.cpp, tests/test_capabilities.cpp, tests/test_security_curve.cpp, tweetnacl/contrib/randombytes/randombytes.h, tweetnacl/src/tweetnacl_base.h
The sodium/tweetnacl detection logic does not yet you disable
encryption if libsodium is installed.
Fixes #1850 in libzmq/master
=> Problem: cannot disable encryption if libsodium is installed

NEWS, src/session_base.cpp
Solution: backport fix from https://github.com/zeromq/libzmq/pull/1511
=> Problem: connection might terminate prematurely

src/tcp_connecter.cpp, src/tcp_listener.cpp
=> fix: sockets are not signed int on Windows

CMakeLists.txt, NEWS, src/config.hpp
This is the fix for [issue 1542](https://github.com/zeromq/libzmq/issues/1542), originally [PR 1543](https://github.com/zeromq/libzmq/pull/1543). It fixes a crash on Windows when port 5905 is already used by another process. Instead, let the OS choose a port which also makes the need for the event or mutex obsolete.
=> Backport fix for issue 1542 to zmq 4.1.x

configure.ac
Only set sparcv9 optimization for sparc64 systems.
This allows to run for example application using zeromq
on sparc32 systems.
Signed-off-by: Waldemar Brodkorb <wbx@uclibc-ng.org>
=> allow to build sparc (v8,leon)

include/zmq.h
Problem occurs on SPARC and ARM CPUs. This commit is a backport of
https://github.com/zeromq/libzmq/commit/d9fb1d36ff2008966af538f722a1f4ab158dbf64 (from
libzmq), first reported in https://github.com/zeromq/libzmq/issues/1325.
=> Fix alignment problem with zmq_msg_t

NEWS, tests/testutil.hpp
Solution: backport https://github.com/zeromq/libzmq/pull/2092 and update NEWS
=> Problem: testutil.hpp fails to build on Windows XP

tweetnacl/contrib/randombytes/winrandom.c
Linux uses case sensitive file system. So we can't find "wincrypt.h" by
"WinCrypt.h".
=> Support cross compile with MinGW on Linux

NEWS, src/socket_base.cpp, tests/test_reqrep_tcp.cpp
Solution: backport PR https://github.com/zeromq/libzmq/pull/2111 to fix issue https://github.com/zeromq/libzmq/issues/2107
=> Problem: zmq_connect with IPv6 "source:port;dest:port" format is broken

.travis.yml, NEWS, src/ctx.cpp, tests/test_inproc_connect.cpp
Solution: backport https://github.com/zeromq/libzmq/pull/2123
Also fix OSX Travis job
=> Problem: zmq_ctx_term asserts with connect-before-bind and sockets with identity over inproc transport

doc/zmq_socket.txt
Problem: zmq_socket doc doesn't mention that router can block on send
Solution: clarify that it may block, and under which conditions
This is a backport of zeromq/libzmq#2148.
=> doc/zmq_socket.txt: clarify that ROUTER can be blocking

src/socket_base.cpp, src/socket_base.hpp
This is a backport of the fix for issue #2158 (PR #2159 and #2160) from the master branch. It fixes concurrent access to the ZMQ_PAIR socket in the socket monitor.
The monitor socket is used concurrently from different threads
and needs protection.
=> Add mutex to socket monitor access

src/pipe.cpp, tests/test_hwm_pubsub.cpp
This is backport of https://github.com/zeromq/libzmq/pull/1649/commits which caused issues in our 4.1.5-based application with ZMQ_STREAM sockets.
=> Merged PR 1649

INSTALL
Documentation also patched in libzmq. 
Closes #151 to document non-support for parallel make check.
=> Update INSTALL to note issues with parallel "make -j check"

NEWS, include/zmq.h
Solution: backport https://github.com/zeromq/libzmq/pull/2177 and https://github.com/zeromq/libzmq/pull/2179 and update NEWS
Quite a few fixes have been piling up on this repo, so I'd like to tag a new bugfix release
=> Problem: pointer union for zmq_msg_t is a hack

src/mechanism.cpp
Solution: check socket type from 0 to 11 to include ZMQ_STREAM
=> Problem: socket_type_string off-by-one error

src/stream_engine.cpp, src/stream_engine.hpp
This pr fix [issues#2254](https://github.com/zeromq/libzmq/issues/2254) which zmq4.x pub msg to sub server run with ZMTP 1.0 protocol, such as zmq 2.x
Same as [https://github.com/zeromq/libzmq/pull/2256](https://github.com/zeromq/libzmq/pull/2256)
=> fix bug zmq4.1.x PUB msg to ZMTP 1.0 SUB svr

src/lb.cpp
This is based on https://github.com/zeromq/zeromq3-x/pull/116/files
=> fix divide by zero in zmq::lb_t::sendpipe

src/socket_base.cpp
Solution: backport the fix
This PR backports the fix to the following issue
https://github.com/zeromq/libzmq/issues/1257
The bug manifests as follows: If the inproc sub socket is connect()-ed/bind()-ed before the inproc pub socket is bind()-ed/connect()-ed, messages will not be received.
=> Problem: pubsub inproc bug not backported

src/router.cpp
Backport fix:
https://github.com/zeromq/libzmq/pull/2622
=> Fix ROUTER's xhas_out() in MANDATORY mode

src/tcp_connecter.cpp
Fixes #164 (EHOSTDOWN from getsockopt must not cause assertion abort; causes SaltStack crashes)
=> Add error code EHOSTDOWN to the list of acceptable error codes.
